language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install -e .
before_script:
- python -m spacy download en
- sciwing develop makedirs
- sciwing develop download
script:
- travis_wait 60 pytest -v -p no:warnings tests -m "not slow"
deploy:
  provider: pypi
  user: abhinavkashyap92
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJDNlYTUzOGE2LTFkMzAtNDUzNC1iYTljLTUxMmI4MjI1Nzg1YgACOHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzY2l3aW5nIl19LCAidmVyc2lvbiI6IDF9AAAGIIPFRacmOXGmuBX08Q3G-FLU3RWRe0ygRdqsKroq7LPG
  on:
    tags: true
  skip_cleanup: true
notifications:
  slack: wing-nus:y2FydrZoKNsNzXcqSqfMhsSl
