wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.25
    framework: torch
    is_jupyter_run: false
    python_version: 3.7.6
bs:
  desc: null
  value: 32
emb_type:
  desc: null
  value: glove_6B_50
epochs:
  desc: null
  value: 2
exp_dir_path:
  desc: null
  value: ./output
exp_name:
  desc: null
  value: sectlabel_bow_random
log_train_metrics_every:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
model_save_dir:
  desc: null
  value: ./output/checkpoints
save_every:
  desc: null
  value: 1
vocab_store_location:
  desc: null
  value: ./output/vocab.json
