exp_name = ""
exp_dir = ""
[dataset]
	name = "parsect_dataset"
	class = "ParsectDataset"
	[dataset.args]
	filename = ""
	max_num_words = 1000
	max_instance_length = 100
	word_vocab_store_location = ""
	debug = false
	debug_dataset_proportion = 0.1
	word_embedding_type = "random"
	word_embedding_dimension = 300