[experiment]
    exp_name = "debug_parsect_dataset"
    exp_dir = "/Users/abhinav/abhi/parsect/parsect/outputs/debug_parsect_dataset"

[dataset]
	name = "train_parsect_dataset"
	class = "ParsectDataset"
	[dataset.args]
	filename = "/Users/abhinav/abhi/parsect/parsect/data/sectLabel.train.data"
	max_num_words = 1000
	max_instance_length = 100
	word_vocab_store_location = "/Users/abhinav/abhi/parsect/parsect/outputs/debug_parsect_dataset/vocab.json"
	debug = false
	debug_dataset_proportion = 0.1
	word_embedding_type = "random"
	word_embedding_dimension = 300
	dataset_type="train"
