[experiment]
    exp_name = "sectlabel-bow-glove"
    exp_dir = "sectlabel_bow_glove_toml"

[dataset]
	class = "SectLabelDataset"
	train_filename="sectLabel.train.data"
	valid_filename="sectLabel.train.data"
	test_filename="sectLabel.train.data"
	[dataset.args]
	max_num_words = 1000
	max_instance_length = 100
	word_vocab_store_location = "sectlabel_bow_glove_toml/vocab.json"
	debug = true
	debug_dataset_proportion = 0.1
	word_embedding_type = "glove_6B_100"
	word_embedding_dimension = 100

[model]
    class="SimpleClassifier"
    encoding_dim=100
    num_classes=23
    classification_layer_bias=true
    [model.encoder]
        emb_dim = 100
        class="BOW_Encoder"
        dropout_value = 0.5
        aggregation_type="sum"
        [[model.encoder.embedder]]
        class="VanillaEmbedder"
        embed="word_vocab"
        freeze=false

[engine]
    batch_size=32
    save_dir="sectlabel_bow_glove_toml/checkpoints"
    num_epochs=1
    save_every=10
    log_train_metrics_every=10
    tensorboard_logdir="debug_parsect_dataset"
    device="cpu"
    gradient_norm_clip_value=5.0
    [engine.metric]
        class="PrecisionRecallFMeasure"
    [engine.optimizer]
        class="Adam"
        lr=1e-3