[experiment]
    exp_name = "sectlabel-bow-elmo"
    exp_dir = "sectlabel_bow_elmo_toml"

[dataset]
	class = "SectLabelDataset"
	train_filename="sectLabel.train.data"
	valid_filename="sectLabel.train.data"
	test_filename="sectLabel.train.data"
	[dataset.args]
	max_num_words = 1000
	max_instance_length = 100
	word_vocab_store_location = "sectlabel_bow_elmo_toml/vocab.json"
	debug = true
	debug_dataset_proportion = 0.1
	word_embedding_type = "random"
	word_embedding_dimension = 300

[model]
    class="SimpleClassifier"
    encoding_dim=1024
    num_classes=23
    classification_layer_bias=true
    [model.encoder]
        class="BOW_Encoder"
        dropout_value = 0.5
        aggregation_type="sum"
        emb_dim = 1024
        [[model.encoder.embedder]]
        class="BowElmoEmbedder"
        emb_dim=1024

[engine]
    batch_size=32
    save_dir="sectlabel_bow_elmo_toml/checkpoints"
    num_epochs=1
    save_every=10
    log_train_metrics_every=10
    device="cpu"
    gradient_norm_clip_value=5.0
    [engine.metric]
        class="PrecisionRecallFMeasure"
    [engine.optimizer]
        class="Adam"
        lr=1e-3