[experiment]
    exp_name = "genericsect-bilstm"
    exp_dir = "genericsect_bilstm_toml"

[dataset]
	class = "GenericSectDataset"
	train_filename="genericSect.train.data"
	valid_filename="genericSect.train.data"
	test_filename="genericSect.train.data"
	[dataset.args]
	max_num_words = 1000
	max_instance_length = 100
	word_vocab_store_location = "genericsect_bilstm_toml/vocab.json"
	debug = true
	debug_dataset_proportion = 0.1
	word_embedding_type = "random"
	word_embedding_dimension = 300

[model]
    class="SimpleClassifier"
    encoding_dim=200
    num_classes=23
    classification_layer_bias=true
    [model.encoder]
        emb_dim = 300
        class="LSTM2VecEncoder"
        dropout_value = 0.5
        combine_strategy="concat"
        bidirectional=true
        device="cpu"
        hidden_dim=100
        [[model.encoder.embedder]]
        class="VanillaEmbedder"
        embed="word_vocab"
        freeze=false


[engine]
    batch_size=32
    save_dir="genericsect_bilstm_toml/checkpoints"
    num_epochs=1
    save_every=10
    log_train_metrics_every=10
    device="cpu"
    gradient_norm_clip_value=5.0
    [engine.metric]
        class="PrecisionRecallFMeasure"
    [engine.optimizer]
        class="Adam"
        lr=1e-3